### ISSUE TITLE
PM Portal - IR Config - Weather Station Scroll Bar Not Functional

### ISSUE THREAD

**Issue by leeensminger** [BC89/PM-Portal-Issues#246]
Issue:

The scroll bar within the Weather Station list does not scroll.  Instead it appears that upon clicking anywhere in the scroll bar, the system is actually selecting a Weather Station.

Steps to recreate:
1. Within the Weather Station list, scroll up or down in the list using the scroll bar.

Resolution: Ensure a mouse click on the scroll bar triggers the scroll actions.

This is related to #244 , and this whole piece may be redesigned.

**Comment by arheimberger** [comment]
Closed
